language: node_js
node_js:
  - node

branches:
  only:
    - staging

cache:
  directories:
    - node_modules

before_install:
 - printf "@wilsongp:registry=https://registry.npmjs.org/" >> ~/.npmrc

script:
   - npm run build

notifications:
  email: # only receive email when the build status changes (someone broke the build!)
    on_failure: change
    on_success: change

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  target_branch: master
  on:
    branch: staging
