language: node_js
node_js:
  - node

branches:
  only:
    - master

cache:
  directories:
    - node_modules

before_install:
 - printf "@wilsongp:registry=https://registry.npmjs.org/" >> ~/.npmrc

before_script:
  - npm install -g --silent @angular/cli

script: # the build step
   - npm run deploy

notifications:
  email: # only receive email when the build status changes (someone broke the build!)
    on_failure: change
    on_success: change

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  target_branch: gh-pages
  on:
    branch: master
